# Generated by Django 5.2.8 on 2025-11-07 11:15

from django.db import migrations, models
'''
migracoes são geradas automaticamente pelos comandos no cmd python manage.py 
makemigrations e python manage.py migrate, e servem para armazenas os objetos
no banco de dados
'''

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article', 
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
